package com.memorytree.enums;

public enum BranchType {
    DEDUCTIVE_REASONING,
    INDUCTIVE_REASONING,
    MATHEMATICAL_COMPUTATION,
    LOGICAL_FALLACY_DETECTION,
    PREMISE_CONSISTENCY_CHECK,
    DEFAULT_LOGIC_CHECK
}